spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      # enabled is relative to the address and port of our running application
      enabled: true
      path: /h2-console
