server:
  port: 8080

logging:
  # Set the log level of the package where the mapper interface is located to DEBUG, so that you can see more detailed SQL execution logs.
  level:
    "io.springcloud.mybatis.mapper": "DEBUG"

spring:
  # MYSQL data source configuration. No need to explain too much.
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST_PORT}/spring_boot_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  # Set the xml configuration file address for mybatis.
  # config-location: "classpath:mybatis/mybatis-config.xml"

  # Loads all files in the 'mapper' directory (regardless of directory hierarchy) with names ending in '-mapper.xml'.
  mapper-locations:
    # this setting is not used
    - "classpath:mapper/**/*-mapper.xml"